"""Residential property held off the investment ledger.

The pipeline ingests investment-account statements; residential property
has no statement feed, so it's a user-maintained table (mirroring
``opening-positions.toml`` / ``cgt-losses.toml``). Each property carries a
purchase cost and a series of dated valuations (manual estimates — there's
no mark feed).

:func:`render_beancount` turns these into a generated
``data/property.beancount`` (a per-property commodity held at cost, valued
by ``price`` directives), and the ``concentration`` / ``net-worth`` reports
fold them in so net worth reflects total wealth, not just the investment
accounts.

The file is gitignored (personal); a committed ``data/property.example.toml``
documents the schema.
"""

from __future__ import annotations

import re
import tomllib
from datetime import date
from decimal import Decimal
from pathlib import Path

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from banking_pipeline.fx.gbp_rates import GbpRateSource
from banking_pipeline.tax.uk.currency import to_gbp

# beancount commodity: 2–24 chars, start with a capital letter, end with a
# capital letter or digit, ``'._-`` allowed between.
_COMMODITY_RE = re.compile(r"^[A-Z][A-Z0-9'._-]{0,22}[A-Z0-9]$")


def _derive_commodity(label: str) -> str:
    """A beancount commodity code from a free-text label.

    Upper-cases and keeps only ``A-Z0-9``; e.g. ``"Torrelodones"`` →
    ``"TORRELODONES"``, ``"Flat 2"`` → ``"FLAT2"``.
    """

    code = re.sub(r"[^A-Z0-9]", "", label.upper())
    return code[:24]


class Valuation(BaseModel):
    model_config = ConfigDict(frozen=True)

    date: date
    value: Decimal  # in the property's currency


class Property(BaseModel):
    """One property: a cost basis plus dated valuations, in its own
    currency (Bristol GBP, Torrelodones EUR). ``commodity`` is the
    beancount commodity code (derived from ``label`` when omitted)."""

    model_config = ConfigDict(frozen=True)

    label: str
    commodity: str
    name: str | None = None  # commodity display name; defaults from label
    country: str  # ISO-3166 alpha-2 — the domicile dimension
    currency: str  # ISO-4217 — the cost/valuation currency
    acquired: date
    purchase_price: Decimal
    valuations: list[Valuation] = []

    @model_validator(mode="before")
    @classmethod
    def _default_commodity(cls, data: object) -> object:
        if isinstance(data, dict) and not data.get("commodity"):
            return {**data, "commodity": _derive_commodity(str(data.get("label", "")))}
        return data

    @field_validator("commodity")
    @classmethod
    def _validate_commodity(cls, value: str) -> str:
        if not _COMMODITY_RE.match(value):
            raise ValueError(
                f"not a valid beancount commodity code: {value!r} "
                "(2–24 chars, A–Z start, A–Z/0–9 end)"
            )
        return value

    @property
    def display_name(self) -> str:
        return self.name or f"{self.label} (residential property)"

    def marks(self) -> list[Valuation]:
        """Valuations sorted by date, with the purchase price seeded on the
        acquisition date when no valuation is given there."""

        marks = list(self.valuations)
        if not any(v.date == self.acquired for v in marks):
            marks.append(Valuation(date=self.acquired, value=self.purchase_price))
        return sorted(marks, key=lambda v: v.date)


def load_properties(path: Path) -> list[Property]:
    """Parse ``path`` into a list of :class:`Property` (one per
    ``[[property]]``)."""

    raw = tomllib.loads(path.read_text(encoding="utf-8"))
    return [Property.model_validate(entry) for entry in raw.get("property", [])]


_ACCOUNT_RE = re.compile(r"[^A-Za-z0-9]")
_HEADER = (
    ";; Property ledger — generated by `banking-pipeline property`.\n"
    ";; Do not edit; edit data/property.toml and regenerate. Included by\n"
    ";; main.beancount. Each property is a commodity held at cost (1 unit),\n"
    ";; revalued by the price directives below, funded against equity (the\n"
    ";; financing already sits on the investment ledger)."
)


def _account_segment(label: str) -> str:
    seg = _ACCOUNT_RE.sub("", label)
    return seg[:1].upper() + seg[1:] if seg else "Unknown"


def _amount(value: Decimal) -> str:
    return f"{value:,.2f}"


def render_beancount(
    properties: list[Property], *, rate_source: GbpRateSource
) -> str:
    """Render the property ledger.

    Each property becomes a commodity opened on its acquisition date,
    acquired at ``1 <COMMODITY> {purchase_price CCY}`` against
    ``Equity:Property:<label>`` (beancount infers the equity leg), and
    revalued by a ``price`` directive per valuation. For a non-GBP property
    a GBP price mark is also emitted (converted via ``rate_source``) so a
    GBP-operating-currency load (Fava) can value it; if no rate is
    available that date the GBP mark is skipped with a ``; WARN`` comment.
    """

    blocks: list[str] = [_HEADER, ""]
    for p in properties:
        seg = _account_segment(p.label)
        asset = f"Assets:Property:{seg}"
        equity = f"Equity:Property:{seg}"
        acq = p.acquired.isoformat()
        blocks += [
            f"{acq} commodity {p.commodity}",
            f'  name: "{p.display_name}"',
            '  asset-class: "property"',
            "",
            f"{acq} open {asset} {p.commodity}",
            f"{acq} open {equity}",
            "",
            f'{acq} * "Acquired {p.label}"',
            f"  {asset}  1 {p.commodity} "
            f"{{{_amount(p.purchase_price)} {p.currency}}}",
            f"  {equity}",
            "",
        ]
        for v in p.marks():
            d = v.date.isoformat()
            blocks.append(f"{d} price {p.commodity}  {_amount(v.value)} {p.currency}")
            if p.currency.upper() != "GBP":
                gbp = to_gbp(
                    v.value, currency=p.currency, on_date=v.date, source=rate_source
                )
                if gbp is None:
                    blocks.append(
                        f"; WARN no GBP rate for {p.currency} "
                        f"{v.date:%Y-%m} — {p.commodity} won't convert to "
                        "GBP in Fava"
                    )
                else:
                    blocks.append(f"{d} price {p.commodity}  {_amount(gbp)} GBP")
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"
